version: "3"
services:
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
    - 9090:9090
    networks:
    - myNetwork
    volumes:
    - prometheus:/etc/prometheus

  grafana:
    image: ghcr.io/vvops/test-work/test-work_grafana:v2
    restart: always #если контаинер упадет то он будет перезапущен ОТКАЗОУСТОЙЧИВОСТЬ
    container_name: grafana_my
    ports:
    - 3000:3000
    networks:
    - myNetwork

volumes:
  prometheus:
    external: true

networks:
  myNetwork:
    driver: bridge
